function t142_checkSize(recid){var el=$("#rec"+recid).find(".t142__submit");if(el.length){var btnheight=el.height()+5;var textheight=el[0].scrollHeight;if(btnheight<textheight){var btntext=el.text();el.addClass("t142__submit-overflowed")}}}
function t650_unifyHeights(recid){if($(window).width()>=960){$('#rec'+recid+' .t650 .t-container .t650__row').each(function(){var t650_highestBox=0,t650_currow=$(this);$('.t650__inner-col',this).each(function(){var t650_curCol=$(this),t650_curText=t650_curCol.find(".t650__text"),t650_curBtn=t650_curCol.find(".t650__btn-container"),t650_curColHeight=t650_curText.outerHeight()+t650_curBtn.outerHeight();if(t650_curColHeight>t650_highestBox){t650_highestBox=t650_curColHeight}});$('.t650__inner-col',this).css('height',t650_highestBox)})}else{$('.t650__inner-col').css('height','auto')}}
function t718_onSuccess(t718_form){var t718_inputsWrapper=t718_form.find('.t-form__inputsbox');var t718_inputsHeight=t718_inputsWrapper.height();var t718_inputsOffset=t718_inputsWrapper.offset().top;var t718_inputsBottom=t718_inputsHeight+t718_inputsOffset;var t718_targetOffset=t718_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t718_target=t718_targetOffset-200}else{var t718_target=t718_targetOffset-100}
if(t718_targetOffset>$(window).scrollTop()||($(document).height()-t718_inputsBottom)<($(window).height()-100)){t718_inputsWrapper.addClass('t718__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t718_target},400);setTimeout(function(){t718_inputsWrapper.addClass('t718__inputsbox_hidden')},400)}
var successurl=t718_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t821_init(recid){var rec=$('#rec'+recid);var el=rec.find('.t821');var isFixed=(el.css('position')=='fixed');var redactorMode=el.hasClass('t821_redactor-mode');if(!redactorMode){el.removeClass('t821__beforeready');if(isFixed&&el.attr('data-bgopacity-two')){t821_changebgopacitymenu(recid);$(window).bind('scroll',t_throttle(function(){t821_changebgopacitymenu(recid)},200))}
if(isFixed&&el.attr('data-appearoffset')){el.removeClass('t821__beforeready');t821_appearMenu(recid);$(window).bind('scroll',t_throttle(function(){t821_appearMenu(recid)},200))}}
t821_setBg(recid);$(window).bind('resize',t_throttle(function(){t821_setBg(recid)},200))}
function t821_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t821").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t821").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t821_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t821").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t821_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t821").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t821_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t821"),burger=el.find(".t821__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t821_opened")})
$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}
function t826_init(recid){var el=$('#rec'+recid);t826_startAnimation(recid);if(!window.isMobile){$(window).bind('resize',t_throttle(function(){$("div:not(.t826__animation) > div[data-galaxy-id="+recid+"]").remove();t826_startAnimation(recid)}))}
if(window.isMobile){$(window).on("orientationchange",function(){$("div:not(.t826__animation) > div[data-galaxy-id="+recid+"]").remove();t826_startAnimation(recid)})}
el.find('.t826').bind('displayChanged',function(){$("div:not(.t826__animation) > div[data-galaxy-id="+recid+"]").remove();t826_startAnimation(recid)})}
function t826_startAnimation(recid){var el=$('#rec'+recid);var GalaxyEl=el.find(".t826__galaxy");var wr=el.find(".t826");var recs=wr.attr("data-galaxy-rec-ids");var wholepage=wr.attr("data-galaxy-whole-page");var vertFlip=wr.attr("data-galaxy-vflip");var color=wr.attr("data-element-color");var opacity=wr.attr("data-element-opacity");var options={'color':(color===""?"#fff":color),'opacity':(opacity===""?1:opacity.replace(/^0?.([0-9])0?$/g,".$1"))};if(options.color.indexOf('#')!==-1){var color=options.color;if(color[1]===color[2]&&color[3]===color[4]&&color[5]===color[6]){options.color="#"+color[1]+color[3]+color[5]}}
if(vertFlip==="yes"){GalaxyEl.addClass("t826__galaxy_flip")}
if($("#allrecords").attr("data-tilda-mode")==="edit"){t826_addAnimation(el.find(".t826__demo"),GalaxyEl,options);return}
if(typeof recs!=="undefined"){recs=recs.split(",");recs.forEach(function(rec,index,array){var curRec=$("#rec"+rec);var curGalaxyEl=GalaxyEl.clone().css("position","absolute");t826_addAnimation(curRec,curGalaxyEl,options)})}else{var nextBlock=el.next(":has(.t-cover)");var prevBlock=el.prev(":has(.t-cover)");var curGalaxyEl=GalaxyEl.clone().css("position","absolute");if(nextBlock.length!==0){t826_addAnimation(nextBlock,curGalaxyEl,options)}else if(prevBlock.length!==0){t826_addAnimation(prevBlock,curGalaxyEl,options)}}
if(wholepage==="yes"){el.find(".t826__animation").css("display","block");t826_addAnimation($("#allrecords"),GalaxyEl.css("position","fixed"),options)}}
function t826_addAnimation(curRec,GalaxyEl,options){curRec.attr("data-animationappear","off").removeClass('r_hidden');var curRecType=curRec.attr("data-record-type");var curRecId=curRec.attr("id");if(curRecType==="396"){curRec.find(".t396__filter").after(GalaxyEl);GalaxyEl.css("z-index","0")}else if(curRecId==="allrecords"){GalaxyEl.css("z-index","-1")}else{var coverWrapper=curRec.find(".t-cover");if(coverWrapper.length>0){coverWrapper.find(".t-cover__filter").after(GalaxyEl);GalaxyEl.css("z-index","0")}else{var wrapper=curRec;if(wrapper.length===0){return!0}
wrapper.append(GalaxyEl);wrapper.css("position","relative");wrapper.children("div").first().css({"position":"relative","z-index":"1"});if(curRecType=="734"||curRecType=="675"){return}
GalaxyEl.css("z-index","0");if(curRecType=="754"||curRecType=="776"||curRecType=="778"||curRecType=="786"){wrapper.children("div").first().css({"z-index":""});GalaxyEl.css("z-index","-1")}}}
t826_runningAnimation(curRec,options)}
function t826_runningAnimation(curRec,options){var starsSetting;if(!window.isMobile){starsSetting=[{name:"near",count:100,speed:50},{name:"mid",count:200,speed:100},{name:"far",count:700,speed:150}]}else{starsSetting=[{name:"near",count:25,speed:50},{name:"mid",count:500,speed:100},{name:"far",count:175,speed:150}]}
var curRecId=curRec.attr("id");var maxHeight=curRec.outerHeight();var maxWidth=curRec.outerWidth();if(typeof curRecId==="undefined"){curRecId="demo"}else if(curRecId==="allrecords"){maxHeight=$(window).height();maxWidth=$(window).width()}
var animationName="t826__galaxy-"+curRecId;curRec.find("#"+animationName).remove();var newStyle=document.createElement("style");newStyle.id=animationName;newStyle.innerHTML="@keyframes "+animationName+"{"+"to{"+"transform:translateY("+(-maxHeight)+"px)"+"}"+"}";starsSetting.forEach(function(value,index,array){var x=Math.round(Math.random()*maxHeight);var y=Math.round(Math.random()*maxWidth);var dot="";if(options.color.indexOf('#')!==-1){dot=x+"px "+y+"px"}else{if(options.opacity<1){dot=x+"px "+y+"px rgba("+options.color+","+options.opacity+")"}else{dot=x+"px "+y+"px rgb("+options.color+")"}}
var countDots=Math.round(array[index].count*maxHeight/2000);for(var i=0;i<countDots;i++){var x=Math.round(Math.random()*maxWidth);var y=Math.round(Math.random()*maxHeight);if(options.color.indexOf('#')!==-1){dot+=", "+x+"px "+y+"px";dot+=", "+x+"px "+(y+maxHeight)+"px"}else{if(options.opacity<1){dot+=", "+x+"px "+y+"px rgba("+options.color+","+options.opacity+")";dot+=", "+x+"px "+(y+maxHeight)+"px rgba("+options.color+","+options.opacity+")"}else{dot+=", "+x+"px "+y+"px rgb("+options.color+")";dot+=", "+x+"px "+(y+maxHeight)+"px rgb("+options.color+")"}}}
var animationDuration=Math.round(array[index].speed*maxHeight/2000);className="t826__galaxy-"+array[index].name+"-"+curRecId;newStyle.innerHTML+="."+className+":after, ."+className+"{"+"box-shadow:"+dot+";"+"animation-duration:"+animationDuration+"s;"+"animation-name:"+animationName+";"+(options.color.indexOf('#')!==-1?"color:"+options.color+";":"")+(options.color.indexOf('#')!==-1&&options.opacity<1?"opacity:"+options.opacity:"")+"}"+"."+className+":after{"+"content:' ';"+"position:absolute;"+"top:"+maxHeight+"px"+"}";curRec.find(".t826__galaxy > .t826__galaxy-wrapper > .t826__galaxy-"+array[index].name).addClass(className)});curRec.prepend(newStyle);curRec.find(".t826__galaxy > .t826__galaxy-wrapper").css("animation-name","t826__galaxy-fadeIn")}
function t975_init(recid){var el_rec=$('#rec'+recid);var el_menu=el_rec.find('.t975');t975_findActiveItem(recid);el_menu.removeClass('t975__beforeready');t975_checkAnchorLinks(recid);t975_detectIphone(el_menu);if(el_menu.attr('data-hidemenuonscroll')||t975_detectIphone(el_menu)){t975_handleScroll(el_menu)}
if($('#tildacopy').length>0&&$(document).height()>800){t975_addCopyrightMargin(el_menu)}}
function t975_addCopyrightMargin(el_menu){var menuHeight=el_menu.height();$('#tildacopy').css('paddingBottom',menuHeight);t975_handleScroll(el_menu)}
function t975_detectIphone(el_menu){var isIphone=/iPhone/.test(navigator.userAgent)&&!window.MSStream;var aspect=window.screen.width/window.screen.height;var iphoneAspect="0.462";if(isIphone&&aspect.toFixed(3)===iphoneAspect){return!0}}
function t975_findActiveItem(recid){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)=='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=='/'){pathname=pathname.slice(1)}
if(pathname==''){pathname='/'}
$(".t975__list-item a[href='"+url+"'] ").addClass('t-active');$(".t975__list-item a[href='"+url+"/']").addClass('t-active');$(".t975__list-item a[href='"+pathname+"']").addClass('t-active');$(".t975__list-item a[href='/"+pathname+"']").addClass('t-active');$(".t975__list-item a[href='"+pathname+"/']").addClass('t-active');$(".t975__list-item a[href='/"+pathname+"/']").addClass('t-active');if(hash){$(".t975__list-item a[href='"+hash+"']").addClass('t-active')}}
function t975_checkAnchorLinks(recid){var navLinks=$('#rec'+recid+" .t975__list-item a:not(.tooltipstered)[href*='#']");if(navLinks.length>0){t975_catchScroll(navLinks,recid)}}
function t975_catchScroll(navLinks,recid){var clickedSectionId=null,sections=new Array(),sectionIdTonavigationLink=[];var el_rec=$('#rec'+recid);var el_menu=el_rec.find('.t975');navLinks=$(navLinks.get().reverse());navLinks.each(function(){var cursection=t975_getSectionByHref($(this));if(typeof cursection.attr('id')!='undefined'){sections.push(cursection)}
sectionIdTonavigationLink[cursection.attr('id')]=$(this)});t975_updateSectionsOffsets(sections);sections.sort(function(a,b){return b.attr('data-offset-top')-a.attr('data-offset-top')});t975_highlightNavLinks(navLinks,sections,sectionIdTonavigationLink,clickedSectionId);navLinks.click(function(){var clickedSection=t975_getSectionByHref($(this));if(!$(this).hasClass('tooltipstered')&&typeof clickedSection.attr('id')!='undefined'){navLinks.removeClass('t-active');$(this).addClass('t-active');clickedSectionId=t975_getSectionByHref($(this)).attr('id')}});$(window).bind('resize',t_throttle(function(){t975_updateSectionsOffsets(sections)}));el_menu.bind('displayChanged',function(){t975_updateSectionsOffsets(sections)});$(window).bind('scroll',t_throttle(function(){clickedSectionId=t975_highlightNavLinks(navLinks,sections,sectionIdTonavigationLink,clickedSectionId)}))}
function t975_updateSectionsOffsets(sections){$(sections).each(function(){var curSection=$(this);curSection.attr('data-offset-top',curSection.offset().top)})}
function t975_getSectionByHref(curlink){var curLinkValue=curlink.attr('href').replace(/\s+/g,'').replace(/.*#/,'');if(curlink.is('[href*="#rec"]')){return $(".r[id='"+curLinkValue+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+curLinkValue+"']")}}
function t975_highlightNavLinks(navLinks,sections,sectionIdTonavigationLink,clickedSectionId){var scrollPosition=$(window).scrollTop(),valueToReturn=clickedSectionId;if(sections.length!=0&&clickedSectionId==null&&sections[sections.length-1].attr('data-offset-top')>scrollPosition+300){navLinks.removeClass('t-active');return null}
$(sections).each(function(e){var curSection=$(this),sectionTop=curSection.attr('data-offset-top'),sectionId=curSection.attr('id'),navLink=sectionIdTonavigationLink[sectionId];if(scrollPosition+300>=sectionTop||(sections[0].attr('id')==sectionId&&scrollPosition>=$(document).height()-$(window).height())){if(clickedSectionId==null&&!navLink.hasClass('t-active')){navLinks.removeClass('t-active');navLink.addClass('t-active');valueToReturn=null}else{if(clickedSectionId!==null&&sectionId==clickedSectionId){valueToReturn=null}}
return!1}});return valueToReturn}
function t975_handleScroll(el_menu){var isScrolling;var lastScrollTop=0;var delta=5;var initialHeight=window.innerHeight;var maxHeight=initialHeight;var menuPadding;$(window).bind('scroll',t_throttle(function(){var currentScrollTop=$(this).scrollTop();if(Math.abs(lastScrollTop-currentScrollTop)<=delta)return;if(t975_detectIphone(el_menu)){if($('#tildacopy').length>0&&$(document).height()>800){var menuHeight=el_menu.outerHeight();$('#tildacopy').css('paddingBottom',menuHeight)}}
if(el_menu.attr('data-hidemenuonscroll')){currentScrollTop>lastScrollTop?el_menu.slideDown(240):el_menu.slideUp()}
lastScrollTop=currentScrollTop}))}